services:
    sheer.imagerotator.listener:
        class: sheer\imagerotator\event\listener
        arguments:
            - '%core.root_path%'
            - '@config'
        tags:
            - { name: event.listener }
